# Generated by Django 5.2.7 on 2025-11-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_readabilityinfo_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
